---
name: PlayerDetects
author: keenanyafiqy
version: 1.0.0
main: keenanyafiqy\PlayerDetects\DetectMain
api: 4.0.0
description: Shows what players are now doing! (Extremely Annoying Plugin in Console)
src-namespace-prefix: keenanyafiqy\PlayerDetects
...
